name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyautogui pynput

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed main.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-macro-exe
          path: dist/main.exe
