name: Release EXE

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyautogui pynput

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed main.py

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
